server:
  port: 8080
  http2:
    enabled: true

spring:
  web:
    resources:
      chain:
        # 开启静态资源缓存
        cache: true
        enabled: true
        compressed: true
      cache:
        # 设置缓存时间
        period: 2592000
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    # 192.168.43.128
    url: jdbc:mysql://192.168.0.100:3306/tik_tube?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 123456
  servlet:
    multipart:
      enabled: true
      max-file-size: 100000000MB
      max-request-size: 1024000000MB

mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml


logging:
  level:
    com:
      buguagaoshu:
        tiktube: debug
  file:
    name: log/spring.log
  logback:
    rollingpolicy:
      max-history: 7